-- SQLite script to insert 30 sample items

INSERT INTO items (name, description, price, stock_quantity, shop_id, category_id, created_at) VALUES
('Parmigiano Reggiano', 'Aged 24 months, 200g wedge', 12.99, 50, 1, 1, datetime('now')),
('Prosciutto di Parma', 'Thinly sliced, 100g package', 9.99, 30, 1, 1, datetime('now')),
('Balsamic Vinegar of Modena', 'Aged 12 years, 100ml bottle', 24.99, 20, 1, 1, datetime('now')),
('Handmade Ceramic Plate', 'Traditional Ravenna design, 25cm diameter', 34.99, 15, 2, 2, datetime('now')),
('Mosaic Coaster Set', 'Set of 4, inspired by Byzantine mosaics', 29.99, 25, 2, 2, datetime('now')),
('Dante''s Divine Comedy', 'Hardcover edition in Italian', 19.99, 40, 3, 3, datetime('now')),
('Ravenna City Guide', 'Comprehensive travel guide, latest edition', 14.99, 60, 3, 3, datetime('now')),
('Local Craft Beer', 'Artisanal IPA, 330ml bottle', 4.99, 100, 4, 4, datetime('now')),
('Sangiovese Wine', 'Locally produced red wine, 750ml bottle', 16.99, 75, 4, 4, datetime('now')),
('Handmade Leather Wallet', 'Genuine Italian leather, brown', 49.99, 10, 5, 5, datetime('now')),
('Silk Scarf', 'Hand-painted with Ravenna motifs', 39.99, 20, 5, 5, datetime('now')),
('Olive Oil', 'Extra virgin, cold-pressed, 500ml bottle', 14.99, 40, 1, 1, datetime('now')),
('Artisanal Pasta', 'Handmade tagliatelle, 500g package', 7.99, 60, 1, 1, datetime('now')),
('Murano Glass Vase', 'Handblown, multicolor, 20cm height', 89.99, 5, 2, 2, datetime('now')),
('Byzantine-style Earrings', 'Gold-plated with mosaic design', 59.99, 15, 2, 2, datetime('now')),
('Italian Cookbook', 'Traditional Emilia-Romagna recipes', 24.99, 30, 3, 3, datetime('now')),
('Ravenna Postcard Set', 'Set of 10 featuring local landmarks', 9.99, 100, 3, 3, datetime('now')),
('Artisanal Gelato', 'Assorted flavors, 500ml tub', 8.99, 40, 4, 4, datetime('now')),
('Local Honey', 'Raw and unfiltered, 250g jar', 6.99, 50, 4, 4, datetime('now')),
('Leather Sandals', 'Handmade, various sizes available', 69.99, 25, 5, 5, datetime('now')),
('Linen Shirt', 'Locally made, unisex design', 54.99, 30, 5, 5, datetime('now')),
('Truffle Oil', 'White truffle infused olive oil, 100ml bottle', 19.99, 15, 1, 1, datetime('now')),
('Aged Pecorino Cheese', '200g wedge', 11.99, 35, 1, 1, datetime('now')),
('Mosaic Kit', 'DIY kit with local designs', 39.99, 20, 2, 2, datetime('now')),
('Ravenna Skyline Print', 'Limited edition, signed by local artist', 79.99, 10, 2, 2, datetime('now')),
('Italian Language Learning Set', 'Book and audio CD', 29.99, 25, 3, 3, datetime('now')),
('Local History Book', 'Illustrated history of Ravenna', 34.99, 20, 3, 3, datetime('now')),
('Craft Limoncello', 'Homemade-style, 500ml bottle', 21.99, 30, 4, 4, datetime('now')),
('Gourmet Coffee Beans', 'Locally roasted, 250g bag', 12.99, 50, 4, 4, datetime('now')),
('Handwoven Beach Bag', 'Made from local reeds', 44.99, 15, 5, 5, datetime('now'));